if( GetLocale() == "deDE" ) then
	
	CDT_ON = "Aktiv"
	CDT_HIDE_TEXT = "Kein Text"
	CDT_HIDE_TIME = "Keine Zeitanzeige"	
	CDT_SHOW_ICONS = "Zeige Icons"
	CDT_SHOW_MINUTES = "Minuten"
	CDT_ALERTS = "Alarme aktivieren"
	CDT_AUTO_RESIZE = "Auto-Resize"
	CDT_LOCK = "Sperren"
	CDT_SORT_BARS = "Balken sortieren"
	CDT_CASCADE_BARS = "Balken nachr\195\188cken"
	CDT_PLAY_SOUND = "Akustisches Signal"
	CDT_BAG_ITEMS = "Items"
	CDT_PET_SKILLS = "Pet Skills"
	CDT_GROW_DOWN = "Nach unten erweitern"
	CDT_BORDER = "DÜnner Rahmen"	
	
	CDT_TEXTURES_CILO = "Cilos Bar Textur"
	CDT_TEXTURES_SMOOTH = "Glatte Textur"
	CDT_TEXTURES_STANDARD = "Standard Textur"
	
	CDT_SKILL_COLOR = "Skill Color"
	CDT_ITEM_COLOR = "Item Color"
	CDT_TIME_COLOR = "Time Color"
	CDT_TEXT_COLOR = "Text Color"
	CDT_BORDER_COLOR = "Border Color"
	
	CDT_OKAY = "Okay"
	CDT_CANCEL = "Abbrechen"
	CDT_GROUPS = "Gruppen"
	
	CDT_COLUMNS = "Spalten"
	CDT_BAR_DISTANCE = "Abstand Balken"
	CDT_BAR_THICKNESS = "Balkenh\195\182he"
	CDT_TRANS = "Transparenz"
	CDT_SCALE = "Skalierung"
	CDT_MIN_ALERT_TIME = "Min Alarm Zeit"
	CDT_MIN_BAR_LENGTH = "Min Balkenlänge"
	CDT_MIN_TIME = "Min Cooldownzeit"
	
	CDT_GAIN_STEALTH = "Ihr bekommt 'Verstohlenheit'."
	CDT_STEALTH_FADES = "'Verstohlenheit' schwindet von Euch."
	CDT_GAIN_PROWL = "Ich bekommt 'Schleichen'."
	CDT_PROWL_FADES = "'Schleichen' schwindet von Euch."
	CDT_GAIN_SHADOWMELD = "Ihr bekommt 'Schattenhaftigkeit'."
	CDT_SHADOWMELD_FADES = "'Schattenhaftigkeit' schwindet von Euch."
	CDT_CATFORM_FADES = "'Katzenform' schwindet von Euch."
	
	CDT_PROWL = "Schleichen"   
	CDT_STEALTH = "Verstohlenheit"   
	CDT_SHADOWMELD = "Schattenhaftigkeit"   
	
	CDT_RENATAKI = "Renatakis Amulett der Bestien"
	CDT_AIMED = "Gezielter Schuss"
	CDT_MULTI = "Mehrfachschuss"
	CDT_ARCANE = "Arkaner Schuss"
	CDT_VOLLEY = "Salve"
	 
	CDT_CS = "K\195\164lteeinbruch"   
	CDT_FN = "Frostnova"   
	CDT_BARRIER = "Eis-Barriere"   
	CDT_COC = "K\195\164ltekegel"   
	CDT_ICEBLOCK = "Eisblock"   
	CDT_FW = "Frost-Zauberschutz"   
	 
	CDT_PREP = "Vorbereitung"   
	CDT_VANISH = "Verschwinden"   
	CDT_CB = "Kaltbl\195\188tigkeit"   
	CDT_SPRINT = "Sprinten"   
	CDT_PREMED = "Konzentration"   
	CDT_BLIND = "Blenden"   
	CDT_EVASION = "Entrinnen"   
	CDT_KICK = "Tritt"   
	CDT_KS = "Nierenhieb"   
	CDT_GS = "Geisterhafter Sto\195\159"   
	CDT_DISTRACT = "Ablenken"   
	CDT_FEINT = "Finte"
	
	CDT_ALWAYS = "Immer"
	CDT_NEVER = "Nie"
	
	CDT_PRECISION = "Dezimalen"
	CDT_ANNOUNCE_SCALE = "Größe d. Alarmmeldung"
	
elseif ( GetLocale() == "frFR") then
	
	CDT_ON = "On"
	CDT_HIDE_TEXT = "Hide Text"
	CDT_HIDE_TIME = "Hide Time"
	CDT_SHOW_ICONS = "Show Icons"
	CDT_SHOW_MINUTES = "Show Minutes"
	CDT_ALERTS = "Alerts"
	CDT_AUTO_RESIZE = "Auto-Resize"
	CDT_LOCK = "Lock"
	CDT_SORT_BARS = "Sort Bars"
	CDT_CASCADE_BARS = "Cascade Bars"
	CDT_PLAY_SOUND = "Play Sound"
	CDT_BAG_ITEMS = "Items"
	CDT_PET_SKILLS = "Pet Skills"
	CDT_GROW_DOWN = "Grow Downwards"
	CDT_BORDER = "Slim Border"
	
	CDT_TEXTURES_CILO = "Cilos Bar Texture"
	CDT_TEXTURES_SMOOTH = "Smooth Bar Texture"
	CDT_TEXTURES_STANDARD = "Standard Bar Texture"
	
	CDT_SKILL_COLOR = "Skill Color"
	CDT_ITEM_COLOR = "Item Color"
	CDT_TIME_COLOR = "Time Color"
	CDT_TEXT_COLOR = "Text Color"
	CDT_BORDER_COLOR = "Border Color"
	
	CDT_OKAY = "Okay"
	CDT_CANCEL = "Cancel"
	CDT_GROUPS = "Groups"
	
	CDT_COLUMNS = "Columns"
	CDT_BAR_DISTANCE = "Bar Distance"
	CDT_BAR_THICKNESS = "Bar Thickness"
	CDT_TRANS = "Overall Transparency"
	CDT_SCALE = "Scale"
	CDT_MIN_ALERT_TIME = "Min Alert Time"
	CDT_MIN_BAR_LENGTH = "Min Bar Length"
	CDT_MIN_TIME = "Min Cooldown Time"
	
	CDT_GAIN_STEALTH = "You gain Stealth."
	CDT_STEALTH_FADES = "Stealth fades from you."
	CDT_GAIN_PROWL = "You gain Prowl."
	CDT_PROWL_FADES = "Prowl fades from you."
	CDT_GAIN_SHADOWMELD = "You gain Shadowmeld."
	CDT_SHADOWMELD_FADES = "Shadowmeld fades from you."
	CDT_CATFORM_FADES = "Cat Form fades from you."
	
	CDT_PROWL = "Prowl"
	CDT_STEALTH = "Stealth"
	CDT_SHADOWMELD = "Shadowmeld"
	
	CDT_RENATAKI = "Renataki's Charm of Beasts"
	CDT_AIMED = "Aimed Shot"
	CDT_MULTI = "Multi-Shot"
	CDT_ARCANE = "Arcane Shot"
	CDT_VOLLEY = "Volley"
	
	CDT_CS = "Cold Snap"
	CDT_FN = "Frost Nova"
	CDT_BARRIER = "Ice Barrier"
	CDT_COC = "Cone of Cold"
	CDT_ICEBLOCK = "Ice Block"
	CDT_FW = "Frost Ward"
	
	CDT_PREP = "Preparation"
	CDT_VANISH = "Vanish"
	CDT_CB = "Cold Blood"
	CDT_SPRINT = "Sprint"
	CDT_PREMED = "Premeditation"
	CDT_BLIND = "Blind"
	CDT_EVASION = "Evasion"
	CDT_KICK = "Kick"
	CDT_KS = "Kidney Shot"
	CDT_GS = "Ghostly Strike"
	CDT_DISTRACT = "Distract"
	CDT_FEINT = "Feint"
	
	CDT_ALWAYS = "Always"
	CDT_NEVER = "Never"
	
	CDT_PRECISION = "Decimals"
	CDT_ANNOUNCE_SCALE = "Announcement Scale"

else
	
	CDT_ON = "On"
	CDT_HIDE_TEXT = "Hide Text"
	CDT_HIDE_TIME = "Hide Time"
	CDT_SHOW_ICONS = "Show Icons"
	CDT_SHOW_MINUTES = "Show Minutes"
	CDT_ALERTS = "Alerts"
	CDT_AUTO_RESIZE = "Auto-Resize"
	CDT_LOCK = "Lock"
	CDT_SORT_BARS = "Sort Bars"
	CDT_CASCADE_BARS = "Cascade Bars"
	CDT_PLAY_SOUND = "Play Sound"
	CDT_BAG_ITEMS = "Items"
	CDT_PET_SKILLS = "Pet Skills"
	CDT_GROW_DOWN = "Grow Downwards"
	CDT_BORDER = "Slim Border"
	
	CDT_TEXTURES_CILO = "Cilos Bar Texture"
	CDT_TEXTURES_SMOOTH = "Smooth Bar Texture"
	CDT_TEXTURES_STANDARD = "Standard Bar Texture"
	
	CDT_SKILL_COLOR = "Skill Color"
	CDT_ITEM_COLOR = "Item Color"
	CDT_TIME_COLOR = "Time Color"
	CDT_TEXT_COLOR = "Text Color"
	CDT_BORDER_COLOR = "Border Color"
	
	CDT_OKAY = "Okay"
	CDT_CANCEL = "Cancel"
	CDT_GROUPS = "Groups"
	
	CDT_COLUMNS = "Columns"
	CDT_BAR_DISTANCE = "Bar Distance"
	CDT_BAR_THICKNESS = "Bar Thickness"
	CDT_TRANS = "Overall Transparency"
	CDT_SCALE = "Scale"
	CDT_MIN_ALERT_TIME = "Min Alert Time"
	CDT_MIN_BAR_LENGTH = "Min Bar Length"
	CDT_MIN_TIME = "Min Cooldown Time"
	
	CDT_GAIN_STEALTH = "You gain Stealth."
	CDT_STEALTH_FADES = "Stealth fades from you."
	CDT_GAIN_PROWL = "You gain Prowl."
	CDT_PROWL_FADES = "Prowl fades from you."
	CDT_GAIN_SHADOWMELD = "You gain Shadowmeld."
	CDT_SHADOWMELD_FADES = "Shadowmeld fades from you."
	CDT_CATFORM_FADES = "Cat Form fades from you."
	
	CDT_PROWL = "Prowl"
	CDT_STEALTH = "Stealth"
	CDT_SHADOWMELD = "Shadowmeld"
	
	CDT_RENATAKI = "Renataki's Charm of Beasts"
	CDT_AIMED = "Aimed Shot"
	CDT_MULTI = "Multi-Shot"
	CDT_ARCANE = "Arcane Shot"
	CDT_VOLLEY = "Volley"
	
	CDT_CS = "Cold Snap"
	CDT_FN = "Frost Nova"
	CDT_BARRIER = "Ice Barrier"
	CDT_COC = "Cone of Cold"
	CDT_ICEBLOCK = "Ice Block"
	CDT_FW = "Frost Ward"
	
	CDT_PREP = "Preparation"
	CDT_VANISH = "Vanish"
	CDT_CB = "Cold Blood"
	CDT_SPRINT = "Sprint"
	CDT_PREMED = "Premeditation"
	CDT_BLIND = "Blind"
	CDT_EVASION = "Evasion"
	CDT_KICK = "Kick"
	CDT_KS = "Kidney Shot"
	CDT_GS = "Ghostly Strike"
	CDT_DISTRACT = "Distract"
	CDT_FEINT = "Feint"
	
	CDT_ALWAYS = "Always"
	CDT_NEVER = "Never"
	
	CDT_PRECISION = "Decimals"
	CDT_ANNOUNCE_SCALE = "Announcement Scale"
end